services:
  - type: web
    name: glow-off
    env: node
    buildCommand: bun install && bun run build
    startCommand: bun .next/standalone/server.js
    envVars:
      - key: NODE_ENV
        value: production

